### ISSUE TITLE
no matching login attempt found [145546287]

### ISSUE THREAD

**Issue by smeevil** [atoy40/meteor-accounts-cas#4]
** UPDATE

Maybe i should have payed attention to the terminal...
account-cas: unexpected error : Only https CAS servers are supported.

Sorry :)

---
Hi there,

We are using RubyCasino as CAS server.
I've added your package to the meteor app and am calling 
```
Meteor.loginWithCas (err, data) ->
      console.log "cas callback"
      console.log err
      console.log data
```
When the call executes the CAS login window opens in a popup, after filling in the credentials the popup closes and the callback is fired.

The err is triggered and contains : no matching login attempt found [145546287]

I'm not really sure what to do about this ?
Should I first notify Meteor that we are attempting a login ?

/Gerard

**Comment by faridblaster** [comment]
Hi @smeevil , did it solved already ?
